; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
workspace_dir = ./build/.pio
src_dir = ./build

[env]
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
board = rpipicow
extra_scripts = pre:transpile.py
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
debug_speed = 10000
debug_init_break = tbreak
build_src_filter =
	-<*>
build_flags =
	-fpermissive
	-fexceptions
	-w
lib_deps =
	SPI
	Wire
	./lib/lvgl
	./lib/Adafruit BusIO
	./lib/Adafruit PN532

[env:release]
build_src_filter =
	+<release/*>

[env:debug]
build_src_filter =
	+<debug/*>
